version: "3.5"
networks:
  nemo-net:
services:
  mysql:
    networks:
      - nemo-net
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="${SQUARE_WITH_ME_DB_PASSWORD}"
  server:
    networks:
      - nemo-net
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:8080"
    depends_on:
      - mysql
    links:
      - mysql
